### ISSUE TITLE
Can the mail mapper truncate the domain befor mapping?

### ISSUE THREAD

**Issue by jcpunk** [OpenSC/pam_pkcs11#20]
For our usage, the user's email address within the certificate is their username on the host.

Example:

```
bob@mydomain.com -> bob
steve@mydomain.com -> steve
```

I like the `ignoredomain` option as I would prefer to validate that `myhost.mydomain.com` is part of `mydomain.com`.  However, I would prefer not to generate direct maps for each host.

Can some kind of "dropdomain" setting be added to the option list in a way that does not alter the behavior of `ignoredomain` but does do a user match without the domain component?

**Comment by LudovicRousseau** [comment]
See https://github.com/OpenSC/pam_pkcs11/blob/master/README.md
