### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/pam_pkcs11#24]
@LudovicRousseau I may be able (and willing :)) to step up to maintain this package (despite its limited usability on Mac :).

In the meanwhile, could you share your reasons for dropping it? Do you use something else in place of `pam_pkcs11`?

**Comment by LudovicRousseau** [comment]
@mouse07410 thanks for the proposal.

I never really used ``pam_pkcs11`` myself.  I used it as a demonstrator of authentication using a smart card.

**Comment by mouse07410** [comment]
OK, thanks. My first goal is to get it running on Mac OS X, as the one supplied with El Capitan just does not work. Situation seems better on Sierra (where I actually do succeed trying "sudo" with smartcard). Then, if things are fine and the stars align - it would be nice to add ECC capability. I can't see beyond that.

**Comment by mouse07410** [comment]
Alright, I think I'll take the chance (if you still want it).

**Comment by amitkumar50** [comment]
Hello LudovicRousseau,
I thought about pam_pkcs11. It reads certificates stored on token(Smart Card) with help of pkcs11 Libraries, then For the verification of the users' certificates, locally stored CA certificates as well as either online or locally accessible CRLs are used.

My query:
If pam_pkcs11 is going to die. On RHEL How smart-cards would get read, how their certs would be read? Is there any alternate way?

Thanks

**Comment by LudovicRousseau** [comment]
Hello @amitkumar50 
I have no idea what RedHat is planning.
I do not plan to maintain pam_pkcs11 but RHEL can continue to use it.

**Comment by mouse07410** [comment]
@LudovicRousseau so would you like me to share your maintenance burden? If so, please feel free to add me as an owner/maintainer. If not - no offense taken. ;-)

**Comment by LudovicRousseau** [comment]
@mouse07410 I just invited you to be part of pam_pkcs11 maintainers
https://github.com/orgs/OpenSC/teams/pam_pkcs11-maintainers

**Comment by mouse07410** [comment]
Thank you! Accepted.
