### ISSUE TITLE
unable to build pam_pkcs11

### ISSUE THREAD

**Issue by amitkumar50** [OpenSC/pam_pkcs11#29]
```
tar -xvf pam_pkcs11-0.6.9.tar.gz 
cd pam_pkcs11-0.6.9/
./configure 
make
make  all-recursive
make[1]: Entering directory `/home/amitkuma2/Desktop/tak_print/pam_pkcs11-0.6.9'
Making all in .
make[2]: Entering directory `/home/amitkuma2/Desktop/tak_print/pam_pkcs11-0.6.9'
make[2]: Leaving directory `/home/amitkuma2/Desktop/tak_print/pam_pkcs11-0.6.9'
Making all in po
make[2]: Entering directory `/home/amitkuma2/Desktop/tak_print/pam_pkcs11-0.6.9/po'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/amitkuma2/Desktop/tak_print/pam_pkcs11-0.6.9/po'
Making all in doc
make[2]: Entering directory `/home/amitkuma2/Desktop/tak_print/pam_pkcs11-0.6.9/doc'
xsltproc \
--stringparam  section.autolabel 1 \
--stringparam  section.label.includes.component.label 1 \
-o mappers_api.html pam_pkcs11.xsl mappers_api.xml
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl"
compilation error: file pam_pkcs11.xsl line 3 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl
make[2]: *** [mappers_api.html] Error 5
make[2]: Leaving directory `/home/amitkuma2/Desktop/tak_print/pam_pkcs11-0.6.9/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/amitkuma2/Desktop/tak_print/pam_pkcs11-0.6.9'
make: *** [all] Error 2`
```

**Comment by amitkumar50** [comment]
https://github.com/OpenSC/pam_pkcs11/wiki ->  The Linux-PAM Application Developers’ Guide. -> https://mirrors.edge.kernel.org/pub/linux/libs/pam/Linux-PAM-html/Linux-PAM_ADG.html -> Sorry, we cannot find your kernels

**Comment by frankmorgner** [comment]
try `./configure --without-docbook`

**Comment by amitkumar50** [comment]
$ make 
make[3]: Entering directory '/root/pam_pkcs11/src/scconf'
  CC       scconf.lo
  CC       parse.lo
  CC       write.lo
  CC       sclex.lo
  CCLD     libscconf.la
make[3]: Leaving directory '/root/pam_pkcs11/src/scconf'
Making all in common
make[3]: Entering directory '/root/pam_pkcs11/src/common'
Making all in .
make[4]: Entering directory '/root/pam_pkcs11/src/common'
  CC       libcommon_la-algorithm.lo
  CC       libcommon_la-cert_vfy.lo
cert_vfy.c: In function 'verify_crl':
cert_vfy.c:146:15: error: storage size of 'obj' isn't known
   X509_OBJECT obj;
               ^~~
cert_vfy.c:159:3: warning: implicit declaration of function 'X509_OBJECT_free_contents'; did you mean 'X509_OBJECT_up_ref_count'? [-Wimplicit-function-declaration]
   X509_OBJECT_free_contents(&obj);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
   X509_OBJECT_up_ref_count

**Comment by amitkumar50** [comment]
its not picking /usr/local/include/openssl/ossl_typ.h
