### ISSUE TITLE
pam_pkcs11-0.6.10.tar.gz README says use non-existent ./configure.  autoconf and autoconf -i both give errors. 

### ISSUE THREAD

**Issue by JanParcel** [OpenSC/pam_pkcs11#31]
pam_pkcs11-pam_pkcs11-0.6.10  $ autoconf -i
 configure.ac:10: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:16: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:18: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:26: error: possibly undefined macro: AM_PROG_AR
configure.ac:30: error: possibly undefined macro: AM_PROG_LEX
configure.ac:34: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:37: error: possibly undefined macro: AC_MSG_ERROR

pam_pkcs11-pam_pkcs11-0.6.10 $ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

**Comment by wolneykien** [comment]
Hi! Works for me.

`$ git checkout pam_pkcs11-0.6.10`
    Note: checking out 'pam_pkcs11-0.6.10'.
    ...
    HEAD is now at b606e3b... 0.6.10

`$ autoreconf -fiv`
    autoreconf-default: Entering directory `.'
    autoreconf-default: configure.ac: not using Gettext
    autoreconf-default: running: aclocal --force -I aclocal
    autoreconf-default: configure.ac: tracing
    autoreconf-default: configure.ac: AM_GNU_GETTEXT is used, but not AM_GNU_GETTEXT_VERSION
    autoreconf-default: running: libtoolize --copy --force --install
    libtoolize-default: putting auxiliary files in `.'.
    libtoolize-default: copying file `./config.guess'
    libtoolize-default: copying file `./config.sub'
    libtoolize-default: copying file `./install-sh'
    libtoolize-default: copying file `./ltmain.sh'
    libtoolize-default: putting macros in `aclocal'.
    libtoolize-default: copying file `aclocal/libtool.m4'
    libtoolize-default: copying file `aclocal/ltoptions.m4'
    libtoolize-default: copying file `aclocal/ltsugar.m4'
    libtoolize-default: copying file `aclocal/ltversion.m4'
    libtoolize-default: copying file `aclocal/lt~obsolete.m4'
    libtoolize-default: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
    libtoolize-default: rerunning libtoolize-default, to keep the correct libtool macros in-tree.
    autoreconf-default: configure.ac: not using Intltool
    autoreconf-default: configure.ac: not using gtk-doc
    autoreconf-default: running: /usr/bin/autoconf-2.60 --force
    autoreconf-default: running: /usr/bin/autoheader-2.60 --force
    autoreconf-default: running: automake --add-missing --copy --force-missing
    configure.ac:26: installing './ar-lib'
    configure.ac:18: installing './compile'
    configure.ac:10: installing './missing'
    doc/Makefile.am:19: warning: shell ls api/*: non-POSIX variable name
    doc/Makefile.am:19: (probably a GNU make extension)
    doc/Makefile.am:26: warning: '%'-style pattern rules are a GNU make extension
    src/common/Makefile.am: installing './depcomp'
    autoreconf-default: Leaving directory `.'

`$ autoreconf --version`
    autoreconf (GNU Autoconf) 2.69
    Copyright (C)  Free Software Foundation, Inc.
    License GPLv3+/Autoconf: GNU GPL version 3 or later
    <http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

**Comment by JanParcel** [comment]
Source https://github.com/OpenSC//pam_pkcs11/archive/pam_pkcs11-0.6.10.tar.gz... 
    downloading... 
    validating signature... skipping (no signature URL)
    validating hash... ok
/usr/bin/touch pam_pkcs11-0.6.10.tar.gz
....
$ gunzip -c pam_pkcs11-0.6.10.tar.gz
$ cd pam_pkcs11-pam_pkcs11-0.6.10/
$ ls
AUTHORS    Makefile.am  TODO             config.log     doc/             src/
COPYING    NEWS         aclocal/         config.rpath*  etc/             tools/
ChangeLog  README       autom4te.cache/  configure*     pam_pkcs11.spec
INSTALL    README.md    bootstrap*       configure.ac   po/

I also can't make api:
$ grep api .gitignore
doc/api
doc/mappers_api.html

autoreconf: running: automake --add-missing --copy --force-missing
.....
configure.ac:10: installing './install-sh'
configure.ac:10: installing './missing'
doc/Makefile.am:19: warning: shell ls api/*: non-POSIX variable name
doc/Makefile.am:19: (probably a GNU make extension)
doc/Makefile.am:26: warning: '%'-style pattern rules are a GNU make extension
src/common/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'

**Comment by LudovicRousseau** [comment]
The source distribution available from github is generated automatically by github and is NOT complete.

You need to download the `.tar.gz` from https://sourceforge.net/projects/opensc/files/pam_pkcs11/ as indicated in https://github.com/OpenSC/pam_pkcs11#download
