### ISSUE TITLE
Not building against OpenSSL 1.1.1 

### ISSUE THREAD

**Issue by Unb9rn** [OpenSC/pam_pkcs11#35]
Fails to build - hangs on 
> make[3]: Leaving directory '/tmp/pam_pkcs11-pam_pkcs11-0.6.10/po'
> touch stamp-po
> make[2]: Leaving directory '/tmp/pam_pkcs11-pam_pkcs11-0.6.10/po'
> Making all in doc
> make[2]: Entering directory '/tmp/pam_pkcs11-pam_pkcs11-0.6.10/doc'
> ls: cannot access 'api/*': No such file or directory

If I try to reconfigure --without-docbook it goes further and fails with:

> cert_vfy.c:174:3: warning: ‘X509_CRL_get_lastUpdate’ is deprecated [-Wdeprecated-declarations]
>    rv = X509_cmp_current_time(X509_CRL_get_lastUpdate(crl));
>    ^~
> In file included from ../common/pam-pkcs11-ossl-compat.h:30,
>                  from cert_st.h:36,
>                  from cert_vfy.h:30,
>                  from cert_vfy.c:18:
> /usr/include/openssl/x509.h:727:1: note: declared here
>  DEPRECATEDIN_1_1_0(ASN1_TIME *X509_CRL_get_lastUpdate(X509_CRL *crl))
>  ^~~~~~~~~~~~~~~~~~
> cert_vfy.c:183:3: warning: ‘X509_CRL_get_nextUpdate’ is deprecated [-Wdeprecated-declarations]
>    rv = X509_cmp_current_time(X509_CRL_get_nextUpdate(crl));
>    ^~
> In file included from ../common/pam-pkcs11-ossl-compat.h:30,
>                  from cert_st.h:36,
>                  from cert_vfy.h:30,
>                  from cert_vfy.c:18:
> /usr/include/openssl/x509.h:728:1: note: declared here
>  DEPRECATEDIN_1_1_0(ASN1_TIME *X509_CRL_get_nextUpdate(X509_CRL *crl))
>  ^~~~~~~~~~~~~~~~~~
> cert_vfy.c: In function ‘check_for_revocation’:
> cert_vfy.c:205:15: error: storage size of ‘obj’ isn’t known
>    X509_OBJECT obj;
>                ^~~
> cert_vfy.c:212:12: error: storage size of ‘crl_pkey’ isn’t known
>    EVP_PKEY crl_pkey;
>             ^~~~~~~~
> make[4]: *** [Makefile:540: libcommon_la-cert_vfy.lo] Error 1
> make[4]: Leaving directory '/tmp/pam_pkcs11-pam_pkcs11-0.6.10/src/common'
> make[3]: *** [Makefile:615: all-recursive] Error 1
> make[3]: Leaving directory '/tmp/pam_pkcs11-pam_pkcs11-0.6.10/src/common'
> make[2]: *** [Makefile:403: all-recursive] Error 1
> make[2]: Leaving directory '/tmp/pam_pkcs11-pam_pkcs11-0.6.10/src'
> make[1]: *** [Makefile:459: all-recursive] Error 1
> make[1]: Leaving directory '/tmp/pam_pkcs11-pam_pkcs11-0.6.10'
> make: *** [Makefile:391: all] Error 2
> 

Building on Arch, GCC 8.3

**Comment by wolneykien** [comment]
Please, have a look at https://packages.altlinux.org/ru/sisyphus/srpms/pam_pkcs11/patches/pam_pkcs11-0.6.10-build-with-openssl11.patch .

**Comment by Unb9rn** [comment]
Looks like it builds that way. Is it going to be merged? Thanks!

**Comment by wolneykien** [comment]
Yes, it's going to be merged.

**Comment by Unb9rn** [comment]
Great! Thanks!
