### ISSUE TITLE
Provide pam-auth-update configuration file?

### ISSUE THREAD

**Issue by LudovicRousseau** [OpenSC/pam_pkcs11#49]
Copy of Ubuntu bug https://bugs.launchpad.net/ubuntu/+source/pam-pkcs11/+bug/1650366

### Problem:

PAM configuration is managed using pam-auth-update.
However, pam-pkcs11 does not provide the necessary description file below /usr/share/pam-configs.
Hence, it must be added manually to the pam configuration.

### Resolution:
pam-pkcs11 should supply a description file in /usr/share/pam-configs similar to the one attached.

```
Name: PKCS11 Smartcard Authentication
Default: yes
Priority: 128
Auth-Type: Primary
Auth:
	[success=end default=ignore]	pam_pkcs11.so
Auth-Initial:
	[success=end default=ignore]	pam_pkcs11.so
```

Regards,
Joachim

**Comment by frankmorgner** [comment]
This configuration tool is Ubuntu specific, I don't think we want to provide that. Please solve that with your distribution package manager if needed. We do have examples, though.

**Comment by LudovicRousseau** [comment]
`pam-auth-update` also exists on Debian.

I opened Debian [Bug#1089160](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1089160) to have the change in Debian and all derivatives (like Ubuntu).

I agree is it Debian specific. The script comes from [debian/local/pam-auth-update](https://salsa.debian.org/vorlon/pam/-/blob/master/debian/local/pam-auth-update?ref_type=heads) of the source pam package.
