### ISSUE TITLE
verify_crl() failed: getting the issuer's public key failed

### ISSUE THREAD

**Issue by DorMordi** [OpenSC/pam_pkcs11#72]
Hi,

I need help please
when I add crl_online to pam_pkcs11.conf in my ubuntu VM and I try to login with smartcard, I get the following error:

ERROR:pam_pkcs11.c:586: verify_certificate() failed: check_for_revocation() failed: verify_crl() failed: getting the issuer's public key failed

Thanks

**Comment by frankmorgner** [comment]
the CA that issued your tokens certificate isn't trusted by your system. You need to place the issuer's certificate into the OpenSSL directory for trusted certificates
