### ISSUE TITLE
LDAP mapper always return 0 users from LDAP due to userCertificate breaking filters

### ISSUE THREAD

**Issue by rapiertg** [OpenSC/pam_pkcs11#77]
Hello,

I am trying to migrate to new os version and I need to upgrade pam_pkcs at the same time. My old working setup was Ubuntu 18.04 with pam_pkcs11 0.6.8 compiled manually. Unfortunatelly it is not possible to build it anymore in modern OS and newer versions of ldap mapper seems broken. Maybe there is something I am missing but:

In 0.6.8 ldap filter that is sent to ldap looks like (&(objectClass=posixAccount)(uid=my_user))
In newer versions it is a bit different - it adds userCertificate to the filter. LDAP unfortunately don't find my user as it seems userCertificate filters are not working (it returns 0 users). I tested a lot of options with ldapsearch and certificates and it just gives no results. Tested it on 2 versions of ldap servers and several different syntax in hex, base64 etc.

Can it be new syntax that is not compatible with ldap? Is there a way to change to previous behaviour?

**Comment by frankmorgner** [comment]
please check the new release and reopen if needed
